#!/bin/bash
# Converts all the sepcified images to be a uniform size being the minimum
# box that holds each of the images (takes the max discovered height and
# max discovered height)

w=$(identify -ping -format '%w\n' "$@" | sort | tail -1)
h=$(identify -ping -format '%h\n' "$@" | sort | tail -1)

echo "Fitting images to ${w}x${h}"

for image in "$@"; do
  if [ -f "$image~" ]; then
    rm "$image~"
  fi
  mv "$image" "$image~"
  echo -e "Fitting $image ...\c"
  convert "$image~" -gravity center -background white -extent ${w}x${h} "$image"
  echo " done."
done

echo -e "Assembling PDF ...\c"
convert "$@" all.pdf
echo " done."
